import { StyleSheet } from "react-native";
import { appFonts, fontSizes, windowHeight, windowWidth } from "@src/themes";
import { appColors } from "@src/themes";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  // Gradient overlay effects
  gradientOverlay1: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  gradientOverlay2: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  gradientOverlay3: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  content: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: windowHeight(60),
    paddingHorizontal: windowWidth(20),
  },
  avatarSection: {
    flex: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarContainer: {
    width: windowWidth(200),
    height: windowWidth(200),
    borderRadius: windowWidth(100),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 16,
  },
  avatar: {
    width: windowWidth(160),
    height: windowWidth(160),
    borderRadius: windowWidth(80),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 12,
  },
  avatarText: {
    fontSize: fontSizes.FONT56,
    fontFamily: appFonts.bold,
    color: appColors.primaryText,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  userInfoSection: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(20),
  },
  userName: {
    fontSize: fontSizes.FONT32,
    fontFamily: appFonts.bold,
    color: appColors.whiteColor,
    textAlign: 'center',
    marginBottom: windowHeight(12),
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
  },
  callStatusText: {
    fontSize: fontSizes.FONT18,
    fontFamily: appFonts.regular,
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    marginBottom: windowHeight(8),
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  durationText: {
    fontSize: fontSizes.FONT20,
    fontFamily: appFonts.medium,
    color: appColors.whiteColor,
    textAlign: 'center',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  controlsSection: {
    flex: 2,
    justifyContent: 'flex-end',
    width: '100%',
  },
  incomingCallControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    marginBottom: windowHeight(40),
  },
  activeCallControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    marginBottom: windowHeight(40),
  },
  outgoingCallControls: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginBottom: windowHeight(40),
  },
  controlButton: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: windowHeight(15),
  },
  buttonIcon: {
    width: windowWidth(75),
    height: windowWidth(75),
    borderRadius: windowWidth(37.5),
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: windowHeight(12),
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  declineIcon: {
    backgroundColor: 'rgba(244, 67, 54, 0.9)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  answerIcon: {
    backgroundColor: 'rgba(76, 175, 80, 0.9)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  endCallIcon: {
    backgroundColor: 'rgba(244, 67, 54, 0.9)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  activeIcon: {
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  buttonIconText: {
    fontSize: fontSizes.FONT28,
    color: appColors.whiteColor,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  controlButtonText: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.medium,
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    marginTop: windowHeight(6),
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  activeButton: {
    opacity: 0.95,
  },
  additionalInfo: {
    alignItems: 'center',
    paddingBottom: windowHeight(20),
  },
  additionalText: {
    fontSize: fontSizes.FONT13,
    fontFamily: appFonts.regular,
    color: 'rgba(255, 255, 255, 0.85)',
    textAlign: 'center',
    marginBottom: windowHeight(10),
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  connectionStatus: {
    fontSize: fontSizes.FONT13,
    fontFamily: appFonts.medium,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  connected: {
    color: 'rgba(76, 175, 80, 0.95)',
  },
  disconnected: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
});

export { styles };