import { StyleSheet } from 'react-native';
import { appColors, appFonts, fontSizes, windowHeight, windowWidth } from '@src/themes';

export const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  loadingAnimation: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  loadingText: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.medium,
    textAlign: 'center',
  },
  heroSection: {
    borderRadius: 20,
    padding: 25,
    marginBottom: 20,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  heroContent: {
    alignItems: 'center',
  },
  logoContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  heroLogo: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  heroTitle: {
    fontSize: fontSizes.FONT24,
    fontFamily: appFonts.bold,
    color: appColors.whiteColor,
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.regular,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
  },
  amountCard: {
    borderRadius: 16,
    padding: 25,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 6,
    position: 'relative',
  },
  amountLabel: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.medium,
    marginBottom: 8,
    opacity: 0.8,
  },
  amountValue: {
    fontSize: fontSizes.FONT32,
    fontFamily: appFonts.bold,
  },
  warningBadge: {
    position: 'absolute',
    top: 15,
    right: 15,
    backgroundColor: appColors.warning + '20',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  warningText: {
    fontSize: fontSizes.FONT10,
    fontFamily: appFonts.medium,
    color: appColors.warnBg,
  },
  detailsCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: fontSizes.FONT18,
    fontFamily: appFonts.bold,
    flex: 1,
  },
  securityBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  securityText: {
    fontSize: fontSizes.FONT10,
    fontFamily: appFonts.medium,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
  },
  detailLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  detailIcon: {
    fontSize: fontSizes.FONT18,
    marginRight: 12,
  },
  detailLabel: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.medium,
    marginBottom: 2,
  },
  detailValue: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.semiBold,
  },
  copyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginLeft: 10,
  },
  copyBtnText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.medium,
  },
  instructionsCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  instructionsTitle: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.bold,
    marginBottom: 15,
  },
  instructionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  instructionStep: {
    width: '48%',
    alignItems: 'center',
    marginBottom: 15,
  },
  stepNumber: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  stepNumberText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.bold,
    color: appColors.whiteColor,
  },
  stepText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.medium,
    textAlign: 'center',
    lineHeight: 16,
  },
  notesContainer: {
    gap: 10,
    marginBottom: 20,
  },
  noteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
  },
  noteIcon: {
    fontSize: fontSizes.FONT16,
    marginRight: 10,
  },
  noteText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.medium,
    flex: 1,
  },
  actionSection: {
    padding: 20,
    borderTopWidth: 1,
    paddingBottom: 30,
  },
  paymentButton: {
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    marginBottom: 12,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  paymentButtonText: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.bold,
    color: appColors.whiteColor,
  },
  cancelBtn: {
    padding: 15,
    alignItems: 'center',
  },
  cancelBtnText: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.medium,
  },
  // Bottom Sheet Styles
  bottomSheetContent: {
    flex: 1,
    padding: 20,
  },
  processingHeader: {
    alignItems: 'center',
    marginBottom: 30,
  },
  processingIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  processingTitle: {
    fontSize: fontSizes.FONT20,
    fontFamily: appFonts.bold,
    marginBottom: 8,
  },
  processingSubtitle: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.regular,
    textAlign: 'center',
  },
  processingSteps: {
    marginBottom: 30,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  stepIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  stepIconText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.bold,
    color: appColors.primary,
  },
  stepConnector: {
    width: 2,
    height: 20,
    backgroundColor: appColors.border,
    marginLeft: 11,
    marginBottom: 5,
  },
  closeButton: {
  padding: 12,
  alignItems: 'center',
  borderRadius: 8,
  borderWidth: 1,
  borderColor: appColors.border,
},
closeButtonText: {
  fontSize: fontSizes.FONT14,
  fontFamily: appFonts.medium,
},
  confirmButton: {
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  confirmButtonText: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.bold,
    color: appColors.whiteColor,
  },
});